/* eslint-disable import/extensions */
import * as React from 'react';

import Toggle from '../components/form/Toggle';

interface Props {

}

const ScrollPage: React.FC<Props> = () => (
  <div className="container">
    <Toggle />


    <div className="Scrollcontent">
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quisquam natus eum inventore ut. Enim quos sed doloribus, porro tempora nobis.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt sint similique omnis ipsum accusamus quis cupiditate sunt rerum nulla voluptatibus aspernatur doloribus eum nemo facere facilis laboriosam magnam autem veniam, fuga veritatis natus! Recusandae eaque nostrum doloribus ipsum fugit sunt at. Voluptatibus provident sunt commodi maiores dignissimos deserunt odio sit officiis tempora, voluptas corporis aliquid ipsa omnis nisi, exercitationem voluptatum veniam autem vitae reiciendis explicabo repudiandae? Quos repudiandae rem aperiam, at autem cupiditate similique accusantium excepturi quis. Consequatur fugiat voluptatum quo ex possimus facere? Culpa explicabo nobis necessitatibus pariatur deserunt quam porro fuga eum quas, dignissimos impedit aperiam perspiciatis commodi, quaerat totam ex itaque error! Ullam beatae, quia laudantium facilis dolorum, est eveniet quo odio cum iste ratione. Aspernatur, quibusdam reprehenderit nihil ex incidunt perspiciatis voluptas dignissimos explicabo, placeat reiciendis praesentium dolores mollitia repellat a nostrum corrupti. Laboriosam distinctio, in nemo unde, non molestiae eaque tenetur iste iure aspernatur alias quas, ut eius earum fugiat error! Fuga eveniet quod accusantium ipsum quaerat beatae, ad saepe labore, sequi, unde ipsam delectus eligendi ex amet impedit earum explicabo doloribus fugiat vel. Quas officiis voluptas animi quos veniam sequi adipisci neque. Aliquam consequuntur accusantium sunt eos illum beatae rerum quisquam laborum optio distinctio, animi facere, harum unde! Hic quo perferendis sint aliquid architecto alias debitis iste non optio id iusto nisi, excepturi, ut officia, odit ipsam quidem? Atque ut suscipit qui fugiat cupiditate sit ratione ex non? Aspernatur cum illo et dolor. Cumque iusto tempore, sint dolore dignissimos vero quae nisi laudantium minus?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt sint similique omnis ipsum accusamus quis cupiditate sunt rerum nulla voluptatibus aspernatur doloribus eum nemo facere facilis laboriosam magnam autem veniam, fuga veritatis natus! Recusandae eaque nostrum doloribus ipsum fugit sunt at. Voluptatibus provident sunt commodi maiores dignissimos deserunt odio sit officiis tempora, voluptas corporis aliquid ipsa omnis nisi, exercitationem voluptatum veniam autem vitae reiciendis explicabo repudiandae? Quos repudiandae rem aperiam, at autem cupiditate similique accusantium excepturi quis. Consequatur fugiat voluptatum quo ex possimus facere? Culpa explicabo nobis necessitatibus pariatur deserunt quam porro fuga eum quas, dignissimos impedit aperiam perspiciatis commodi, quaerat totam ex itaque error! Ullam beatae, quia laudantium facilis dolorum, est eveniet quo odio cum iste ratione. Aspernatur, quibusdam reprehenderit nihil ex incidunt perspiciatis voluptas dignissimos explicabo, placeat reiciendis praesentium dolores mollitia repellat a nostrum corrupti. Laboriosam distinctio, in nemo unde, non molestiae eaque tenetur iste iure aspernatur alias quas, ut eius earum fugiat error! Fuga eveniet quod accusantium ipsum quaerat beatae, ad saepe labore, sequi, unde ipsam delectus eligendi ex amet impedit earum explicabo doloribus fugiat vel. Quas officiis voluptas animi quos veniam sequi adipisci neque. Aliquam consequuntur accusantium sunt eos illum beatae rerum quisquam laborum optio distinctio, animi facere, harum unde! Hic quo perferendis sint aliquid architecto alias debitis iste non optio id iusto nisi, excepturi, ut officia, odit ipsam quidem? Atque ut suscipit qui fugiat cupiditate sit ratione ex non? Aspernatur cum illo et dolor. Cumque iusto tempore, sint dolore dignissimos vero quae nisi laudantium minus?</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt sint similique omnis ipsum accusamus quis cupiditate sunt rerum nulla voluptatibus aspernatur doloribus eum nemo facere facilis laboriosam magnam autem veniam, fuga veritatis natus! Recusandae eaque nostrum doloribus ipsum fugit sunt at. Voluptatibus provident sunt commodi maiores dignissimos deserunt odio sit officiis tempora, voluptas corporis aliquid ipsa omnis nisi, exercitationem voluptatum veniam autem vitae reiciendis explicabo repudiandae? Quos repudiandae rem aperiam, at autem cupiditate similique accusantium excepturi quis. Consequatur fugiat voluptatum quo ex possimus facere? Culpa explicabo nobis necessitatibus pariatur deserunt quam porro fuga eum quas, dignissimos impedit aperiam perspiciatis commodi, quaerat totam ex itaque error! Ullam beatae, quia laudantium facilis dolorum, est eveniet quo odio cum iste ratione. Aspernatur, quibusdam reprehenderit nihil ex incidunt perspiciatis voluptas dignissimos explicabo, placeat reiciendis praesentium dolores mollitia repellat a nostrum corrupti. Laboriosam distinctio, in nemo unde, non molestiae eaque tenetur iste iure aspernatur alias quas, ut eius earum fugiat error! Fuga eveniet quod accusantium ipsum quaerat beatae, ad saepe labore, sequi, unde ipsam delectus eligendi ex amet impedit earum explicabo doloribus fugiat vel. Quas officiis voluptas animi quos veniam sequi adipisci neque. Aliquam consequuntur accusantium sunt eos illum beatae rerum quisquam laborum optio distinctio, animi facere, harum unde! Hic quo perferendis sint aliquid architecto alias debitis iste non optio id iusto nisi, excepturi, ut officia, odit ipsam quidem? Atque ut suscipit qui fugiat cupiditate sit ratione ex non? Aspernatur cum illo et dolor. Cumque iusto tempore, sint dolore dignissimos vero quae nisi laudantium minus?</p>
    </div>
  </div>
);
export default ScrollPage;
